### ISSUE TITLE
Autoscaling is broken

### ISSUE THREAD

**Issue by JaredJacobsen** [pocesar/actor-twitter-scraper#21]
When I run this scraper on the Apify platform with lots of extra RAM and CPUs, the number of concurrent processes remains at 1. Isn't it supposed to automatically scale the number of concurrent processes to take full advantage of available compute resources?

**Comment by pocesar** [comment]
@JaredJacobsen the scraper requires a dedicated foreground window and tab for scrolling and clicking, the page is JS-heavy and is CPU intensive. it's hardcoded to use max concurrency 1, since the default memory on platform is to use 4GB (1 vCPU) https://github.com/pocesar/actor-twitter-scraper/blob/ece0939126df46fa9d5872fd342308ae557a3d29/src/main.js#L214
but I can make it configurable, it's most likely not going to scale on default memory settings

**Comment by JaredJacobsen** [comment]
If you could make it configurable, that would be awesome. I was using it on a machine with 32 GBs of RAM and expected it to scale to at least 8 concurrent processes of 4GB each.

**Comment by pocesar** [comment]
this was fixed on latest @JaredJacobsen 😄
